kind: Namespace
apiVersion: v1
metadata:
  name: my-python-project
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: receive
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: receive
            image: tftest/receive
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
